# Generated by Django 2.2.3 on 2019-07-29 13:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 7, 29, 13, 21, 19, 411322, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
