# Generated by Django 2.2.3 on 2019-07-02 16:12

from django.db import migrations, models
import django.db.models.deletion
import main.utilities


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Product')),
                ('content', models.TextField(verbose_name='Description')),
                ('price', models.FloatField(default=0, verbose_name='Price')),
                ('contacts', models.TextField(verbose_name='Contacts')),
                ('image', models.ImageField(blank=True, upload_to=main.utilities.get_timestamp_path, verbose_name='Image')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Need to output?')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Published')),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.SubRubric', verbose_name='Rubric')),
            ],
            options={
                'verbose_name': 'Ad',
                'verbose_name_plural': 'Ads',
                'ordering': ['-created_at'],
            },
        ),
    ]
